# Use an official OpenJDK runtime as the base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Spring Boot application JAR file into the container at /app
COPY target/First-Docker-Test-App-0.0.1-SNAPSHOT.jar app.jar

# Define the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "app.jar"]