apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: my-namespace
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9091
      protocol: TCP
  selector:
    app: myapp
